language: objective-c
osx_image: xcode8.2
xcode_project: GithubStatusKit.xcodeproj
xcode_scheme: GithubStatusKit
script:
- xcodebuild -project GithubStatusKit.xcodeproj -scheme GithubStatusKit -destination 'platform=iOS Simulator,id=1FD54EA7-5A25-4D6F-8599-D6F7687DA4EE,OS=10.2' clean test
